//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
//namespace DriveWheel_Upg
//{
public static class DriveWheel_UpgClipboard
{
	[NonSerialized]
	public static bool default_saved;
	
	[NonSerialized]
	public static float AdjustMaxSpeedFraction_default;
	
	[NonSerialized]
	public static float DamperScalar_default;
	
	[NonSerialized]
	public static float SpringScalar_default;
	
	[NonSerialized]
	public static float AdjustTractionFraction_default;
	
	[NonSerialized]
	public static float AdjustBrakeFraction_default;
	
	[NonSerialized]
	public static float WheelMode_default;

	[NonSerialized]
	public static float FacingDirectionFloat_default;
	


	//public static enumShieldType type_defualt;
	
	public static void SaveAsDefault( DriveWheel_Upg P)
	{
		DriveWheel_UpgClipboard.default_saved = true ;
		DriveWheel_UpgClipboard.AdjustMaxSpeedFraction_default = P.AdjustMaxSpeedFraction ;
		DriveWheel_UpgClipboard.DamperScalar_default = P.DamperScalar ;
		DriveWheel_UpgClipboard.SpringScalar_default = P.SpringScalar ;
		DriveWheel_UpgClipboard.AdjustTractionFraction_default = P.AdjustTractionFraction ;
		DriveWheel_UpgClipboard.AdjustBrakeFraction_default = P.AdjustBrakeFraction ;
		DriveWheel_UpgClipboard.WheelMode_default = P.WheelMode ;
		DriveWheel_UpgClipboard.FacingDirectionFloat_default = P.FacingDirectionFloat ;
		//DriveWheel_UpgClipboard.type_defualt = P.type;
	}
	
	public static void LoadDefault( DriveWheel_Upg P)
	{
		if (DriveWheel_UpgClipboard.default_saved)
		{
			P.AdjustMaxSpeedFraction = DriveWheel_UpgClipboard.AdjustMaxSpeedFraction_default ;
			P.DamperScalar = DriveWheel_UpgClipboard.DamperScalar_default ;
			P.SpringScalar = DriveWheel_UpgClipboard.SpringScalar_default ;
			P.AdjustTractionFraction = DriveWheel_UpgClipboard.AdjustTractionFraction_default ;
			P.AdjustBrakeFraction = DriveWheel_UpgClipboard.AdjustBrakeFraction_default ;
			P.AdjustBrakeFraction = DriveWheel_UpgClipboard.AdjustBrakeFraction_default ;
			P.WheelMode = DriveWheel_UpgClipboard.WheelMode_default ;				

			//P.SetWheelMode ( P.WheelMode ) ;

			//P.SetFacingDirection ( P.FacingDirectionFloat ) ;

			//P.DamperSpringInit() ;
			//P.DamperSpringScaling() ;
			//P.ApplyInitSuspentionParam() ;

			// P.SetShieldSizeAndPosition();
			//P.StuffChangedSyncIt();

		}
	}
}
//}

